// Post-match player ratings, 1.0-10.0. Pure functions -- take a stat line,
// return a number. Two tracks: outfield (position-aware) and goalkeeper
// (separate formula entirely, since a keeper's job bears no resemblance to
// an outfield player's).

import type { PlayerPosition } from '../types';

function clampRating(value: number): number {
  const clamped = Math.min(10, Math.max(1, value));
  return Math.round(clamped * 10) / 10;
}

export type OutfieldMatchStats = {
  position: Exclude<PlayerPosition, 'GK'>;
  started: boolean;
  minutesPlayed: number;
  goals: number;
  assists: number;
  shotsOnTarget: number;
  shotsOffTarget: number;
  keyPasses: number;
  passesAttempted: number;
  passesCompleted: number;
  tackles: number;
  interceptions: number;
  duelsWon: number;
  duelsLost: number;
  /** True if the player's side kept a clean sheet this match. */
  cleanSheet: boolean;
  /** Own team's goals conceded this match -- only penalized for DF. */
  goalsConceded: number;
  yellowCards: number;
  redCards: number;
  ownGoals: number;
  penaltiesMissed: number;
};

const GOAL_BONUS: Record<Exclude<PlayerPosition, 'GK'>, number> = { FW: 1.0, MF: 1.2, DF: 1.5 };

export function rateOutfieldPlayer(stats: OutfieldMatchStats): number {
  let rating = 6.0;

  rating += stats.goals * GOAL_BONUS[stats.position];
  rating += stats.assists * 0.7;

  rating += stats.shotsOnTarget * 0.1;
  rating -= stats.shotsOffTarget * 0.05;
  rating += stats.keyPasses * 0.15;

  if (stats.passesAttempted > 0) {
    const completionRate = stats.passesCompleted / stats.passesAttempted;
    if (completionRate > 0.85) rating += 0.3;
    else if (completionRate < 0.65) rating -= 0.3;
  }

  rating += stats.tackles * 0.1;
  rating += stats.interceptions * 0.1;

  const duelsTotal = stats.duelsWon + stats.duelsLost;
  if (duelsTotal > 0) {
    const winRate = stats.duelsWon / duelsTotal;
    if (winRate > 0.6) rating += 0.2;
    else if (winRate < 0.4) rating -= 0.2;
  }

  if (stats.cleanSheet) {
    if (stats.position === 'DF') rating += 0.4;
    else if (stats.position === 'MF') rating += 0.2;
  }
  if (stats.position === 'DF') {
    rating -= stats.goalsConceded * 0.15;
  }

  rating -= stats.yellowCards * 0.3;
  rating -= stats.redCards * 1.5;
  rating -= stats.ownGoals * 1.2;
  rating -= stats.penaltiesMissed * 0.8;

  // A substitute appearance under 20 minutes shouldn't swing wildly off a
  // handful of stats -- pull the result back toward the 6.0 baseline.
  if (!stats.started && stats.minutesPlayed < 20) {
    rating = 6.0 + (rating - 6.0) * 0.4;
  }

  return clampRating(rating);
}

export type GoalkeeperMatchStats = {
  started: boolean;
  minutesPlayed: number;
  saves: number;
  cleanSheet: boolean;
  goalsConceded: number;
  /** Not generated by our own simulation (no penalty-award modeling yet), but supported. */
  penaltiesSaved?: number;
  /** Not generated by our own simulation, but supported for a future data source. */
  errorsLeadingToGoal?: number;
};

export function rateGoalkeeper(stats: GoalkeeperMatchStats): number {
  let rating = 6.0;

  rating += stats.saves * 0.25;
  if (stats.cleanSheet) rating += 1.0;
  rating -= stats.goalsConceded * 0.4;
  rating += (stats.penaltiesSaved ?? 0) * 1.0;
  rating -= (stats.errorsLeadingToGoal ?? 0) * 1.0;

  if (!stats.started && stats.minutesPlayed < 20) {
    rating = 6.0 + (rating - 6.0) * 0.4;
  }

  return clampRating(rating);
}

export type MotmCandidate = { playerId: string; rating: number; goals: number; assists: number };

/** Highest rating wins; ties broken by goals, then assists. Null for an empty match. */
export function pickManOfTheMatch(candidates: MotmCandidate[]): string | null {
  if (candidates.length === 0) return null;
  const best = [...candidates].sort((a, b) => {
    if (b.rating !== a.rating) return b.rating - a.rating;
    if (b.goals !== a.goals) return b.goals - a.goals;
    return b.assists - a.assists;
  })[0];
  return best.playerId;
}
